Repository OpenDevUFCG/roadmap-cc, pull requests merged in 2019-03, with the labels that each got.

#16 Cria CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#18 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#19 Traduz template de bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#30 Adiciona estrutura nuxt padrão pra o projeto
  README.md
  assets/README.md
  assets/roadmap.pdf
  components/Logo.vue
  components/README.md
  jest.config.js
  layouts/README.md
  layouts/default.vue
  middleware/README.md
  nuxt.config.js
  package.json
  pages/README.md
  pages/index.vue
  plugins/README.md
  static/README.md
  static/favicon.ico
  static/icon.png
  store/README.md
  test/Logo.spec.js
  yarn.lock
Labels: em progresso

#31 Adiciona guia de contribuidor
  .github/GIFS/fork.gif
  .github/GIFS/pr.gif
  .github/GIFS/taskboard.gif
  CONTRIBUTING.md
Labels: documentação

#36 Adiciona guia de versionamento
  README.md
Labels: documentação

#35 Adiciona política de branchs
  CONTRIBUTING.md
Labels: documentação

#34 Adiciona dependencias D3
  .babelrc
  .editorconfig
  .eslintrc.js
  .gitignore
  .prettierrc
  .travis.yml
  package-lock.json
  package.json
  yarn.lock
Labels: codificação

#39 Adiciona links com referencias para secoes
  CONTRIBUTING.md
Labels: "good first issue", documentação

#43 Configura componente principal
  components/GraphicVisualization.vue
  components/Logo.vue
  pages/index.vue
  static/favicon.ico
Labels: codificação

#45 44 obter dados disciplinas
  .eslintrc.js
  CNAME
  components/GraphicVisualization.vue
Labels: codificação
