Repository OpenDevUFCG/roadmap-cc, pull requests merged in 2022-05, with the labels that each got.

#146 Adição de novo componente a home das trilhas + correções em estilização
  public/index.html
  src/Components/About/About.jsx
  src/Components/MapsPoint/index.js
  src/Components/Navbar/Navbar.jsx
  src/Components/Pt-Br.js
  src/Components/Trilhas/Card.js
  src/Components/Trilhas/Trilhas-home.jsx
  src/Styles/Card.scss
  src/Styles/Navbar.scss
  src/Styles/Styles.css
  src/Styles/Styles.css.map
  src/Styles/Trilha.scss
  src/Styles/Trilhas-home.scss
  src/Styles/about.scss
  src/assets/icons/point.svg
  src/assets/logo/logo-roadmap.svg
Labels: hacktoberfest, hacktoberfest-accepted

#151 Remove o uso do vega lite
  package-lock.json
  package.json
  src/App2.js
  src/Components/Home/Home.js
  src/Components/Home/d3-force-layout.js
  src/Components/Home/miserables.js
  src/Components/Home/vis-home.json
  src/Components/TrilhaInfra/Trilha-infra.jsx
  src/Components/TrilhaInfra/d3-graph.js
  src/routes.js
Labels: codificação, em andamento

#142 Adiciona texto na trilha trilha de ciência de dados
  src/Components/Trilhas/data.js
Labels: hacktoberfest, hacktoberfest-accepted

#148 Adiciona versão inicial do layout de árvore para as trilhas
  package-lock.json
  src/App2.js
  src/AppTrilhas.js
  src/Components/TrilhaDados/Trilha-dados.jsx
  src/Components/TrilhaInfra/d3-graph.js
  src/d3-graph2.js
  src/dataAPI.js
  src/routes.js
Labels: hacktoberfest, hacktoberfest-accepted

#163 Correcao de conflitos
  src/AppTrilhas.js
  src/Components/Home/Home.js
  src/Components/Trilhas/data.js
  src/routes.js
Labels: codificação

#165 correcao de estilizacao no card
  src/Components/Card/styles.module.css
Labels: codificação

#166 Correcao de css + adicao de tamanho fonte
  public/index.html
  src/Components/Home/Home.js
  src/Components/Home/styles.module.css
  src/Components/Pt-Br.js
Labels: codificação
